-- Q1: List the first name, last name, and email of all customers in the customer table.
SELECT first_name, last_name, email FROM customer;

-- Q2: List all customers who live in the city “London”. Include their first name, last name, and city.
SELECT * FROM address;
SELECT * FROM city;

SELECT cx.first_name,
    cx.last_name,
    c.city
FROM customer cx
    JOIN address a ON cx.address_id = a.address_id
    JOIN city c ON a.city_id = c.city_id
WHERE c.city = 'London';

-- Q3: Find the total number of rentals for each customer. 
-- List the customer’s first name, last name, and the total number of rentals, sorted from highest to lowest rentals.
SELECT cx.first_name,
    cx.last_name,
    COUNT(r.customer_id) AS rentals
FROM customer cx
    JOIN rental r ON cx.customer_id = r.customer_id
GROUP BY cx.customer_id
ORDER BY rentals DESC;

-- Q4: Find the top 5 films with the highest number of rentals. Show film_id, title, and number of rentals.
SELECT f.film_id,
    f.title,
    COUNT(*) AS rentals
FROM film f
    JOIN inventory i ON f.film_id = i.film_id
    JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.film_id
ORDER BY rentals DESC
LIMIT 5;

-- Q5: Find the total revenue generated by each film. Include film_id, title, and total revenue, sorted from highest to lowest revenue.
